# Generated by Django 5.2.6 on 2026-09-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("number", models.IntegerField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tables",
                "ordering": ["number"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("number__gt", 0)),
                        name="table_number_positive",
                    )
                ],
            },
        ),
    ]
