# Generated by Django 5.2.6 on 2026-09-30 16:18

import apps.users.managers
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username_normalized", models.CharField(max_length=64)),
                ("ip", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["username_normalized", "ip", "created_at"],
                        name="loginfailure_user_ip_created",
                    ),
                    models.Index(fields=["created_at"], name="loginfailure_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=32, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Admin"), ("CASHIER", "Cashier")],
                        default="CASHIER",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("DISABLED", "Disabled")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("token_version", models.PositiveIntegerField(default=0)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("username"),
                        name="uniq_user_username_ci",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("username__regex", "^[a-z0-9._]{3,32}$")),
                        name="user_username_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["ADMIN", "CASHIER"])),
                        name="user_role_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["ACTIVE", "DISABLED"])),
                        name="user_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="user_name_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("token_version__gte", 0)),
                        name="user_token_version_gte_0",
                    ),
                ],
            },
            managers=[
                ("objects", apps.users.managers.UserManager()),
            ],
        ),
    ]
