# Generated by Django 5.2.6 on 2026-09-30 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("shifts", "0001_initial"),
        ("tables", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.BigIntegerField(db_index=True, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("DINE_IN", "DINE_IN"), ("TAKEAWAY", "TAKEAWAY")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("PAID", "PAID"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("subtotal_minor", models.BigIntegerField(default=0)),
                ("discount_minor", models.BigIntegerField(default=0)),
                ("total_minor", models.BigIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orders",
                        to="shifts.shift",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orders",
                        to="tables.table",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("unit_price_minor", models.BigIntegerField()),
                ("qty", models.IntegerField()),
                ("subtotal_minor", models.BigIntegerField()),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="order_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_lines",
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                condition=models.Q(("status", "OPEN"), ("table__isnull", False)),
                fields=["table"],
                name="uniq_open_order_per_table",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal_minor__gte", 0)),
                name="order_subtotal_minor_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_minor__gte", 0)),
                name="order_discount_minor_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_minor__gte", 0)),
                name="order_total_minor_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_minor__lte", models.F("subtotal_minor"))),
                name="order_discount_lte_subtotal",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type", "DINE_IN"), ("table__isnull", False)),
                    models.Q(("type", "TAKEAWAY"), ("table__isnull", True)),
                    _connector="OR",
                ),
                name="order_table_type_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price_minor__gt", 0)),
                name="orderline_unit_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty__gte", 1), ("qty__lte", 999)),
                name="orderline_qty_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal_minor__gt", 0)),
                name="orderline_subtotal_positive",
            ),
        ),
    ]
