# Generated by Django 5.2.6 on 2026-09-30 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "OPEN"), ("CLOSED", "CLOSED")],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("opening_balance_minor", models.BigIntegerField(default=0)),
                (
                    "sales_total_minor_snapshot",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "cash_total_minor_snapshot",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "card_total_minor_snapshot",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("orders_count_snapshot", models.IntegerField(blank=True, null=True)),
                ("counted_cash_minor", models.BigIntegerField(blank=True, null=True)),
                ("difference_minor", models.BigIntegerField(blank=True, null=True)),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shifts",
                "ordering": ["-opened_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "OPEN")),
                        fields=("cashier",),
                        name="uniq_open_shift_per_cashier",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("opening_balance_minor__gte", 0)),
                        name="shift_opening_balance_positive",
                    ),
                ],
            },
        ),
    ]
