# Generated by Django 5.2.6 on 2026-09-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "business_name",
                    models.CharField(default="كاشيري", max_length=80),
                ),
                (
                    "receipt_footer",
                    models.CharField(
                        blank=True, default="شكرًا لزيارتكم", max_length=200
                    ),
                ),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pk", 1)),
                        name="store_settings_singleton_id",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("business_name", ""), _negated=True),
                        name="store_settings_business_name_not_blank",
                    ),
                ],
            },
        ),
    ]
