# Generated by Django 5.2.6 on 2026-09-30 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("DISABLED", "DISABLED")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("coffee", "coffee"),
                            ("tea", "tea"),
                            ("juice", "juice"),
                            ("soft_drink", "soft_drink"),
                            ("water", "water"),
                            ("breakfast", "breakfast"),
                            ("sandwich", "sandwich"),
                            ("burger", "burger"),
                            ("pizza", "pizza"),
                            ("grill", "grill"),
                            ("chicken", "chicken"),
                            ("pasta", "pasta"),
                            ("rice", "rice"),
                            ("salad", "salad"),
                            ("soup", "soup"),
                            ("appetizer", "appetizer"),
                            ("dessert", "dessert"),
                            ("cake", "cake"),
                            ("ice_cream", "ice_cream"),
                            ("bakery", "bakery"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("price_minor", models.BigIntegerField()),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("DISABLED", "DISABLED")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "db_table": "items",
                "ordering": ["category__sort_order", "category__name", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "name"), name="uniq_item_name_per_category"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price_minor__gt", 0)),
                        name="item_price_positive",
                    ),
                ],
            },
        ),
    ]
